version: '3.7'
services:
    app:
        build:
            context: .docker-compose
            dockerfile: Dockerfile
            args:
                USER: '${WWWUSER}'
                UID: '${WWWUSERUID:-1000}'
        volumes:
            - '.:/var/www/'
        restart: unless-stopped
        container_name: 'finance-service-app'
        networks:
            - finance_service_network
            - database_mysql_network
#        depends_on:
#            - redis
    nginx:
        image: nginx:1.17-alpine
        container_name: 'finance_service_nginx'
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www
            - ./.docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - finance_service_network
            - database_mysql_network
#    mailpit:
#        image: 'axllent/mailpit:latest'
#        ports:
#            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
#            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
#        networks:
#            - sail
networks:
    finance_service_network:
        driver: bridge
    database_mysql_network:
        external: true

