<?php

namespace App\Integrations\MainApp;

use Illuminate\Support\Facades\Cache;

class MainAppConfig
{
    const CRON_FINANCE_INVOICE_REMINDER_HOUR = 'CRON_FINANCE_INVOICE_REMINDER_HOUR';
    const CRON_FINANCE_INVOICE_REMINDER_EMAIL = 'CRON_FINANCE_INVOICE_REMINDER_EMAIL';
    const CRON_FINANCE_INVOICE_REMINDER_EMAIL_SUBJECT = 'CRON_FINANCE_INVOICE_REMINDER_EMAIL_SUBJECT';
    const CRON_FINANCE_INVOICE_REMINDER_EMAIL_MESSAGE = 'CRON_FINANCE_INVOICE_REMINDER_EMAIL_MESSAGE';
    const CRON_FINANCE_INVOICE_REMINDER_EMAIL_LINK = 'CRON_FINANCE_INVOICE_REMINDER_EMAIL_LINK';
    const CRON_FINANCE_INVOICE_REMINDER_SMS = 'CRON_FINANCE_INVOICE_REMINDER_SMS';
    const CRON_FINANCE_INVOICE_REMINDER_SMS_MESSAGE = 'CRON_FINANCE_INVOICE_REMINDER_SMS_MESSAGE';
    const CRON_FINANCE_INVOICE_REMINDER_SMS_LINK = 'CRON_FINANCE_INVOICE_REMINDER_SMS_LINK';
    const FINANCE_INVOICE_CREATE_MESSAGE = 'FINANCE_INVOICE_CREATE_MESSAGE';
    const FINANCE_INVOICE_CREATE_SUBJECT = 'FINANCE_INVOICE_CREATE_SUBJECT';
    const INVOICE_NUMBER_CURRENT_PAID_INVOICE_NUMBER = 'INVOICE_NUMBER_CURRENT_PAID_INVOICE_NUMBER';
    const INVOICE_NUMBER_CURRENT_REFUNDED_INVOICE_NUMBER = 'INVOICE_NUMBER_CURRENT_REFUNDED_INVOICE_NUMBER';
    const INVOICE_NUMBER_CURRENT_INVOICE_ID = 'INVOICE_NUMBER_CURRENT_INVOICE_ID';
    const INVOICE_NUMBER_CURRENT_FISCAL_YEAR = 'INVOICE_NUMBER_CURRENT_FISCAL_YEAR';
    const FINANCE_SERVICE_DEFAULT_TAX = 'FINANCE_SERVICE_DEFAULT_TAX';
    const RAHKARAN_FISCAL_YEAR_REF = 'RAHKARAN_FISCAL_YEAR_REF';
    const FINANCE_TAX_TOTAL_PERCENT = 'FINANCE_TAX_TOTAL_PERCENT';

    public static function get($key, $default = null, $refresh = false)
    {
        if ($refresh) {
            try {
                $value = MainAppAPIService::getConfig($key);
            } catch (\Exception $e) {
                $value = $default;
            }
            Cache::put($key, $value, config('cache.main_app_config_ttl', 3600));
        } else {
            $value = Cache::get($key);
        }

        return $value;

    }
}
